Fixing 3 Bugs related to new Dates features
overture-stack/SONG pull request #697
Opened 2020-11-17 15:44 UTC by joneubank

- Update analysis will set UpdatedAt to now
  https://app.zenhub.com/workspaces/argo-mega-board-all-repos-5c8c8637777e5f767e486217/issues/overture-stack/song/691
- Analysis State History will be sorted by date (ascending)
  https://app.zenhub.com/workspaces/argo-mega-board-all-repos-5c8c8637777e5f767e486217/issues/overture-stack/song/689
- Get Analyses by study will show populated publish times
  https://app.zenhub.com/workspaces/argo-mega-board-all-repos-5c8c8637777e5f767e486217/issues/overture-stack/song/690

2020-11-17 21:06 UTC, andricDu approved these changes

2020-11-18 13:43 UTC, rtisma requested changes
Needs tests for:
1. asserting `analysisStateHistory` changes are sorted chronologically from newest to oldest
2. add a test to ensure when an analysis is update, a newer timestamp is set

2020-11-18 13:43 UTC, rtisma commented on song-server/src/main/java/bio/overture/song/server/model/analysis/AnalysisStateChange.java
> +
delete newline

2020-11-18 18:31 UTC, joneubank commented
Force push after rebase to develop.

2020-11-19 21:37 UTC, rtisma approved these changes

2020-11-19 21:40 UTC, merged